import {Fragment} from "react";

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import HomeModule from 'modules/Home'
const Home: NextPage = () => {
  //tips:不要在这里写复杂逻辑或异步请求，存在重复执行
  return (
      <Fragment>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <HomeModule/>
      </Fragment>
  )
}

export default Home
