/**
 * @Author: HimalayaAnt
 * @Date: 2021/12/23
 **/
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const Mine: NextPage = () => {
    //tips:不要在这里写复杂逻辑或异步请求，存在重复执行
    return (
        <div className={styles.container}>
            <Head>
                <title>我的音乐</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}

export default Mine
